require('dotenv').config();

const {
  DATABASE_URL,
  DATABASE_HOST,
  DATABASE_PORT,
  DATABASE_NAME,
  DATABASE_USERNAME,
  DATABASE_PASSWORD,
  SNIPPETS_CLIENT_URL = 'http://localhost:5000',
} = process.env;

module.exports = {
  DATABASE_URL:
    DATABASE_URL ||
    `postgres://${DATABASE_USERNAME}:${DATABASE_PASSWORD}@${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}`,
  CLIENT_URL: SNIPPETS_CLIENT_URL,
};
