name: snippets

services:
  db:
    image: postgres:16-alpine
    env_file: .env
    volumes:
      - snippets-data:/var/lib/postgresql/data
    restart: unless-stopped

  api:
    build: .
    env_file: .env
    ports:
      - 3002:3000
    depends_on:
      - db
    restart: unless-stopped

volumes:
  snippets-data:
    name: snippets-data
